#!/Users/amitani/Library/PyPy/pypy3.6-v7.3.0-osx64/bin/pypy3
import sys

input = sys.stdin.readline


# Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, Q = map(int, input().split())
    A = [0] * N
    B = [0] * N
    for i in range(N - 1):
        A[i], B[i] = map(int, input().split())
    C = [0] * Q
    D = [0] * Q
    for i in range(Q):
        C[i], D[i] = map(int, input().split())

    E = [[] for _ in range(N + 1)]
    E[0].append(1)
    for a, b in zip(A, B):
        E[a].append(b)
        E[b].append(a)

    depth = [-1] * (N + 1)  # -1: not processed
    to_visit = [(1, 0)]  # head, pre
    while to_visit:
        head, pre = to_visit.pop()
        #print(head, pre, c, d)
        depth[head] = depth[pre] + 1
        for b in E[head]:
            if b != pre:
                to_visit.append((b, head))
    for c, d in zip(C, D):
        if depth[c] % 2 == depth[d] % 2:
            print('Town')
        else:
            print('Road')

    pass


if __name__ == '__main__':
    main()
